name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull cristianortizheano/platform:latest
    - name: Delete Old docker container
      run: sudo docker rm -f platform-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 4200:4200 --name platform-container cristianortizheano/platform:latest